// Date: 30/03/2013 17:13:37
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package me.rushmead.saber.client.models;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Saber1Model extends ModelBase
{
  //fields
    ModelRenderer cube1;
    ModelRenderer cube2;
    ModelRenderer cube3;
    ModelRenderer cube4;
    ModelRenderer cube5;
    ModelRenderer cube6;
    ModelRenderer cube7;
    ModelRenderer cube8;
    ModelRenderer cube9;
    ModelRenderer cube10;
    ModelRenderer cube11;
    ModelRenderer cube12;
    ModelRenderer cube13;
    ModelRenderer cube14;
    ModelRenderer cube15;
    ModelRenderer cube16;
    ModelRenderer cube17;
    ModelRenderer cube18;
    ModelRenderer cube19;
    ModelRenderer cube20;
  
  public Saber1Model()
  {
    textureWidth = 128;
    textureHeight = 64;
    
    cube1 = new ModelRenderer(this, 0, 0);
    cube1.addBox(0F, 0F, 0F, 1, 3, 3);
    cube1.setRotationPoint(0F, 21F, -8F);
    cube1.setTextureSize(128, 64);
    cube1.mirror = true;
    setRotation(cube1, 0F, 0F, 0F);
    cube2 = new ModelRenderer(this, 0, 62);
    cube2.addBox(0F, 0F, 0F, 1, 1, 1);
    cube2.setRotationPoint(0F, 20F, -4F);
    cube2.setTextureSize(128, 64);
    cube2.mirror = true;
    setRotation(cube2, 0F, 0F, 0F);
    cube3 = new ModelRenderer(this, 4, 62);
    cube3.addBox(0F, 0F, 0F, 1, 1, 1);
    cube3.setRotationPoint(0F, 21F, -5F);
    cube3.setTextureSize(128, 64);
    cube3.mirror = true;
    setRotation(cube3, 0F, 0F, 0F);
    cube4 = new ModelRenderer(this, 8, 62);
    cube4.addBox(0F, 0F, 0F, 1, 1, 1);
    cube4.setRotationPoint(0F, 20F, -5F);
    cube4.setTextureSize(128, 64);
    cube4.mirror = true;
    setRotation(cube4, 0F, 0F, 0F);
    cube5 = new ModelRenderer(this, 12, 62);
    cube5.addBox(0F, 0F, 0F, 1, 1, 1);
    cube5.setRotationPoint(0F, 19F, -5F);
    cube5.setTextureSize(128, 64);
    cube5.mirror = true;
    setRotation(cube5, 0F, 0F, 0F);
    cube6 = new ModelRenderer(this, 16, 62);
    cube6.addBox(0F, 0F, 0F, 1, 1, 1);
    cube6.setRotationPoint(0F, 20F, -6F);
    cube6.setTextureSize(128, 64);
    cube6.mirror = true;
    setRotation(cube6, 0F, 0F, 0F);
    cube7 = new ModelRenderer(this, 21, 56);
    cube7.addBox(0F, 0F, 0F, 1, 4, 4);
    cube7.setRotationPoint(0F, 16F, -4F);
    cube7.setTextureSize(128, 64);
    cube7.mirror = true;
    setRotation(cube7, 0F, 0F, 0F);
    cube8 = new ModelRenderer(this, 33, 60);
    cube8.addBox(0F, 0F, 0F, 1, 2, 2);
    cube8.setRotationPoint(0F, 15F, -5F);
    cube8.setTextureSize(128, 64);
    cube8.mirror = true;
    setRotation(cube8, 0F, 0F, 0F);
    cube9 = new ModelRenderer(this, 53, 60);
    cube9.addBox(0F, 0F, 0F, 1, 2, 2);
    cube9.setRotationPoint(0F, 19F, -1F);
    cube9.setTextureSize(128, 64);
    cube9.mirror = true;
    setRotation(cube9, 0F, 0F, 0F);
    cube10 = new ModelRenderer(this, 40, 58);
    cube10.addBox(0F, 0F, 0F, 1, 1, 5);
    cube10.setRotationPoint(0F, 15F, -2F);
    cube10.setTextureSize(128, 64);
    cube10.mirror = true;
    setRotation(cube10, 0F, 0F, 0F);
    cube11 = new ModelRenderer(this, 20, 0);
    cube11.addBox(0F, 0F, 0F, 1, 1, 1);
    cube11.setRotationPoint(0F, 16F, 0F);
    cube11.setTextureSize(128, 64);
    cube11.mirror = true;
    setRotation(cube11, 0F, 0F, 0F);
    cube12 = new ModelRenderer(this, 25, 0);
    cube12.addBox(0F, 0F, 0F, 1, 1, 1);
    cube12.setRotationPoint(0F, 16F, 1F);
    cube12.setTextureSize(128, 64);
    cube12.mirror = true;
    setRotation(cube12, 0F, 0F, 0F);
    cube13 = new ModelRenderer(this, 26, 0);
    cube13.addBox(0F, 0F, 0F, 1, 1, 1);
    cube13.setRotationPoint(0F, 17F, 0F);
    cube13.setTextureSize(128, 64);
    cube13.mirror = true;
    setRotation(cube13, 0F, 0F, 0F);
    cube14 = new ModelRenderer(this, 40, 58);
    cube14.addBox(0F, 0F, 0F, 1, 1, 5);
    cube14.setRotationPoint(0F, 14F, -1F);
    cube14.setTextureSize(128, 64);
    cube14.mirror = true;
    setRotation(cube14, 0F, 0F, 0F);
    cube15 = new ModelRenderer(this, 40, 58);
    cube15.addBox(0F, 0F, 0F, 1, 1, 5);
    cube15.setRotationPoint(0F, 13F, 0F);
    cube15.setTextureSize(128, 64);
    cube15.mirror = true;
    setRotation(cube15, 0F, 0F, 0F);
    cube16 = new ModelRenderer(this, 40, 58);
    cube16.addBox(0F, 0F, 0F, 1, 1, 5);
    cube16.setRotationPoint(0F, 12F, 1F);
    cube16.setTextureSize(128, 64);
    cube16.mirror = true;
    setRotation(cube16, 0F, 0F, 0F);
    cube17 = new ModelRenderer(this, 40, 58);
    cube17.addBox(0F, 0F, 0F, 1, 1, 5);
    cube17.setRotationPoint(0F, 11F, 2F);
    cube17.setTextureSize(128, 64);
    cube17.mirror = true;
    setRotation(cube17, 0F, 0F, 0F);
    cube18 = new ModelRenderer(this, 40, 58);
    cube18.addBox(0F, 0F, 0F, 1, 1, 5);
    cube18.setRotationPoint(0F, 10F, 3F);
    cube18.setTextureSize(128, 64);
    cube18.mirror = true;
    setRotation(cube18, 0F, 0F, 0F);
    cube19 = new ModelRenderer(this, 52, 0);
    cube19.addBox(0F, 0F, 0F, 1, 1, 4);
    cube19.setRotationPoint(0F, 9F, 4F);
    cube19.setTextureSize(128, 64);
    cube19.mirror = true;
    setRotation(cube19, 0F, 0F, 0F);
    cube20 = new ModelRenderer(this, 63, 0);
    cube20.addBox(0F, 0F, 0F, 1, 1, 3);
    cube20.setRotationPoint(0F, 8F, 5F);
    cube20.setTextureSize(128, 64);
    cube20.mirror = true;
    setRotation(cube20, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
	  super.render(par1Entity, par2, par3, par4, par5, par6, par7);
	    setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    cube1.render(par7);
    cube2.render(par7);
    cube3.render(par7);
    cube4.render(par7);
    cube5.render(par7);
    cube6.render(par7);
    cube7.render(par7);
    cube8.render(par7);
    cube9.render(par7);
    cube10.render(par7);
    cube11.render(par7);
    cube12.render(par7);
    cube13.render(par7);
    cube14.render(par7);
    cube15.render(par7);
    cube16.render(par7);
    cube17.render(par7);
    cube18.render(par7);
    cube19.render(par7);
    cube20.render(par7);
    
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
  }

}
